apiVersion: v1
kind: Pod
metadata:
  name: cpu-stress
spec:
  containers:
  - name: cpu-stress
    image: polinux/stress
    resources:
      requests:
        memory: "50Mi"
    command: ["stress"]
    args: ["--cpu", "1"]