kind: Service
apiVersion: v1
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  selector:
    k8s-app: alertmanager
  type: NodePort
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 30001