apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-deployment
  labels:
    k8s-app: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: alertmanager
  template:
    metadata:
      labels:
        k8s-app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager
          volumeMounts:
            - name: alertmanager-config
              mountPath: /etc/alertmanager/
          ports:
            - containerPort: 9093
          resources:
            requests:
              cpu: 10m
              memory: 100Mi
      volumes:
        - name: alertmanager-config
          configMap:
            name: alertmanager-config