apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  labels:
    name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'dima-test'
    receivers:
      - name: 'dima-test'
        webhook_configs:
        - url: 'https://webhook.site/1b5fb204-1100-448a-b3cf-273bdfa2eff4' 